object Versions {
    const val gradlePlugin = "4.2.1"
    const val kotlin = "1.8.10"
    const val appCompat = "1.3.0"
    const val material = "1.3.0"
    const val constraintLayout = "1.0.1"
    const val circleimageview = "3.0.0"
    const val koin = "3.2.0"
    const val retrofit = "2.7.1"
    const val retrofitConverter = "2.9.0"
    const val retrofitLogging = "4.9.0"
    const val lifecycle = "2.6.0"
    const val room = "2.4.0"
    const val jUnit = "4.12"
    const val jUnitExt = "1.1.3"
    const val androidxRunner = "1.1.1"
    const val androidxRules = "1.1.0"
    const val androidxExpresso = "3.3.0"
    const val androidxCore = "1.4.0"
    const val mockK = "1.12.4"
    const val coroutines = "1.7.1"
    const val coreTesting = "2.0.1"
    const val composeVersion = "1.4.2"
    const val composeMaterial = "1.3.1"
    const val composeActivity = "1.6.1"
    const val navigationCompose = "2.4.1"
    const val coilKt = "2.1.0"
    const val paging = "1.0.0-alpha14"
    const val animateNavcontroller = "0.24.5-alpha"
    const val  roboletric = "4.8"
    const val playCore = "1.10.0"
    const val dataStore = "1.0.0"
    const val lottieCompose = "6.0.0"
    const val tooling = "1.1.1"
    const val composeCustomview = "1.2.0-alpha01"
    const val composePoolingContainer = "1.0.0-rc01"
    const val composeJunit = "1.0.0-rc01"
    const val splashCore = "1.0.0-rc01"
    const val firebaseBom = "32.1.0"
    const val livedata = "2.5.1"
    const val googleServices = "20.4.1"
    const val coroutinesPlayServices = "1.6.4"
    const val composeBom = "2023.01.00"
}

object Dependencies {
    val appCompat = "androidx.appcompat:appcompat:${Versions.appCompat}"
    val kotlin = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${Versions.kotlin}"
    val materialDesign = "com.google.android.material:material:${Versions.material}"
    val junit = "junit:junit:${Versions.jUnit}"
    val lifecycle = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.lifecycle}"
    val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    val coroutinesCore = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.coroutines}"
    val coroutinesAndroid =
        "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.coroutines}"
    val koinAndroid = "io.insert-koin:koin-android:${Versions.koin}"
    val koinCompose = "io.insert-koin:koin-androidx-compose:${Versions.koin}"
    val circleimageview = "de.hdodenhof:circleimageview:${Versions.circleimageview}"
    val room = "androidx.room:room-runtime:${Versions.room}"
    val roomCoroutines = "androidx.room:room-ktx:${Versions.room}"
    val lifecycleKtx = "androidx.lifecycle:lifecycle-runtime-ktx:${Versions.lifecycle}"
    val lifecycleCompose = "androidx.lifecycle:lifecycle-runtime-compose:${Versions.lifecycle}"
    val gson  = "com.squareup.retrofit2:converter-gson:${Versions.retrofitConverter}"
    val retrofitLogger  = "com.squareup.okhttp3:logging-interceptor:${Versions.retrofitLogging}"
    val animationNavController  = "com.google.accompanist:accompanist-navigation-animation:${Versions.animateNavcontroller}"
    val playCore = "com.google.android.play:core:${Versions.playCore}"
    val dataStore = "androidx.datastore:datastore-preferences:${Versions.dataStore}"
    val splashCore = "androidx.core:core-splashscreen:${Versions.splashCore}"
    val lifecycleLivedata = "androidx.lifecycle:lifecycle-livedata-ktx:${Versions.livedata}"
    val googleAuth = "com.google.android.gms:play-services-auth:${Versions.googleServices}"
    val coroutinesPlayservices = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services:${Versions.coroutinesPlayServices}"
}

object Compose {
    val navigationCompose = "androidx.navigation:navigation-compose:${Versions.navigationCompose}"
    val coilKt  = "io.coil-kt:coil-compose:${Versions.coilKt}"
    val constraintLayout = "androidx.constraintlayout:constraintlayout-compose:${Versions.constraintLayout}"
    val composeActivity = "androidx.activity:activity-compose:${Versions.composeActivity}"
    val lottieCompose = "com.airbnb.android:lottie-compose:${Versions.lottieCompose}"
    val composeUi = "androidx.compose.ui:ui"
    val composeMaterial = "androidx.compose.material:material:${Versions.composeMaterial}"
    val composePreview = "androidx.compose.ui:ui-tooling-preview"
    val pagingCompose  = "androidx.paging:paging-compose:${Versions.paging}"
    val composeTooling = "androidx.compose.ui:ui-tooling"
    val composeCustomview = "androidx.customview:customview:${Versions.composeCustomview}"
    val composePoolingContainer = "androidx.customview:customview-poolingcontainer:${Versions.composePoolingContainer}"
    val composeBom = "androidx.compose:compose-bom:${Versions.composeBom}"
}


object AnnotationProcessor {
    val room = "androidx.room:room-compiler:${Versions.room}"
    val lifecycle = "androidx.lifecycle:lifecycle-compiler:${Versions.lifecycle}"
}

object Tests {
    val koinTest = "io.insert-koin:koin-test:${Versions.koin}"
    val coreTesting = "androidx.arch.core:core-testing:${Versions.coreTesting}"
    val mockk = "io.mockk:mockk:${Versions.mockK}"
    val androidxCore = "androidx.test:core-ktx:${Versions.androidxCore}"
    val jUnit = "junit:junit:${Versions.jUnit}"
    val jUnitExt = "androidx.test.ext:junit-ktx:${Versions.jUnitExt}"
    val coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-test:${Versions.coroutines}"
    val roboletric = "org.robolectric:robolectric:${Versions.roboletric}"
    val composeJunit = "androidx.compose.ui:ui-test-junit4"
    val composeUITest = "androidx.compose.ui:ui-test-manifest"
}

object Firebase {
    val firebaseBom = "com.google.firebase:firebase-bom:${Versions.firebaseBom}"
    val firebaseAuth = "com.google.firebase:firebase-auth-ktx"
    val firebaseMessaging = "com.google.firebase:firebase-messaging-ktx"
    val firebaseInApp = "com.google.firebase:firebase-inappmessaging-ktx"
    val firebaseAnalytics = "com.google.firebase:firebase-analytics-ktx"
    val firebaseFirestore = "com.google.firebase:firebase-firestore-ktx"
    val firebaseConfig = "com.google.firebase:firebase-config-ktx"
}