name: Deploy App for Firebase Distribution

on:
  push:
    branches:
      - release
      - main
      - develop
  pull_request:
    branches:
      - release
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create file
        run: cat /home/runner/work/MyNextBook/MyNextBook/app/google-services.json | base64

      - name: Putting data
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > /home/runner/work/MyNextBook/MyNextBook/app/google-services.json

      - name: Download Build AAB
        uses: actions/download-artifact@v2
        with:
          name: app-release
          path: app/build/outputs/bundle/prodRelease

      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          releaseNotesFile: app/src/main/play/release-notes/release-notes.txt
          groups: Testers-CICD-MyNextBook
          file: app/build/outputs/bundle/prodRelease/app-dev-release.aab